### ISSUE TITLE
Feature request: output matrices with uneven bins

### ISSUE THREAD

**Issue by NelleV** [nservant/HiC-Pro#1]
Hi there,

Thank you very much for this pipeline! I'd like to create matrices with uneven size bins, and it is currently not possible. More precisely, I'd like to create matrices with exactly one RE site per bin.

Cheers,
Nelle

**Comment by nservant** [comment]
Since v2.7.1b, we can now generate maps at the restriction fragment resolution. To do so, specified BIN_SIZE=-1 inn the configuration file. Note that the ICE normalization will be run as for the other resolution although its assumption of equal visibility of bins might require further exploration in this case
