### ISSUE TITLE
About the valid reads

### ISSUE THREAD

**Issue by wenjiexiaomeng** [nservant/HiC-Pro#107]
Hi,

Thanks for your excellent tools, this help me a lot。
I am confusing about the statistics of the valid data, why FF pairs is the most part of the valid interaction？The paper says each part should be 25% , but my result is quite different with this, and I cant figure it out , do you have any idea about this?

Best,
Wenjie
############################################################################
Below is my result
![image](https://user-images.githubusercontent.com/25812010/32528268-1580c2dc-c46d-11e7-8513-1af92e2a84ca.png)

**Comment by nservant** [comment]
Hi,

Indeed, we expect the same proportion of FF/RF/FR/RR, in theory as the ligation is expected to be a random process. In practice, we often have a few percent more FR reads as you notice.
I think there could be several explanations for that and it might be good to discuss with people who made the 3C library.

Otherwise, did you look at the distribution of fragment length ? My feeling is that, if the digestion did not work very well, you can have a fraction of longer 'undigested' fragments spanning several restriction fragments. When you will sequence these longer undigested fragments, they will be assigned to FR reads ... which could explain this higher FR fraction.
If you want to play a bit, you can set the variable MIN/MAX_INSERT_SIZE in the config file, to restrict the analysis to DNA fragments with a size in a given range. It would be interesting to see whether it will impact the fraction of FR pairs.
And here, you already did it, but discarding the religation events also tends to decrease this level of FR reads.

To conclude, although I think it could still be good to play a bit with the parameters, your data looks good ! I think you can go ahead ;)
Best
