### ISSUE TITLE
Warning : no SNPs found at position XY  N ignored

### ISSUE THREAD

**Issue by Tocci89** [nservant/HiC-Pro#119]
Hi nservant,
I'm using HiC-Pro for allele-specific analysis, I'm running the program version 2.9.0 in parallel mode. At the end of first step everything seems ok, exept for the markAlleleSpecific.log. Here, in some positions I get the following message: "Warning : no SNPs found at position chrA:B. N ignored" (where A is the name of the chromosome and B is the coordinate). I get  496547 of these warnings out of a total 1788788 SNPs. I also checked some of the warning positions both in the VCF and in the masked reference, they're listed into the VCF and the positions are correctly masked into the fasta. So my questions are: 
1- Is this number of warnings acceptable to go on with the analysis? 
2- What this warnings are due to?
3-What is the expected frequency of 1-1 1-0 2-2 2-0 1-2 0-0 3- pairs?
Thanks in advance!

**Comment by nservant** [comment]
Hi
The Warning is launch when for a given SNPs, bases that do not correspond to the expected genotype is found. For instance, at position 1, you expect to have the allele A or G, but Hi-C-pro found other nucleotides (C,T) at this position.
Thus, in theory, you do not expect to have such warning. It might be due to issues in the VCF file.
A simple way to double check that, is to choose a SNPs, and to look into IGV whether you have the good nucleotide.
Then, from my experience on Mouse cross, we usually expect around 25% of reads from genome1 (1-1 + 0-1) and 25% from genome2 (2-2 + 0-2)
Best

**Comment by Tocci89** [comment]
Still didn't fixed the warnings. Anyway from a deeper look into markAlleleSpecific.log I've found out that most of the lines are printed several times. Once sorted, the file contains 88033 unique warning lines instead of 496547. Don't know if this is something expected.

**Comment by nservant** [comment]
Did you check your VCF file ? I mean did you really looked at the position reported in the warning what's going on in term of genotypes that you provide, and in term of expected SNPs ??
