### ISSUE TITLE
hicpro2juicebox.sh sort error?

### ISSUE THREAD

**Issue by liufuyan2016** [nservant/HiC-Pro#147]
sh /share/nas1/liufuyan/HiC-Pro-master//bin/utils/hicpro2juicebox.sh -i all.validPairs.mod.chr -g Os.len -j /share/nas30/liufuyan/HiC-Pro-master/HiC-Pro_2.10.0/bin/utils/juicer_tools.1.7.6_jcuda.0.8.jar -o ./ -r digest_final_genome.fa.bed.filter.chr   
HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
./tmp
**sort: write failed: /tmp/sortzSYb49: No space left on device**
Running Juicebox ...
./tmp/96727_allValidPairs.pre_juicebox_sorted does not exist or does not contain any reads.
done !

**Comment by sowmyaiyer** [comment]
I encountered the same error. This is because unix sort uses /tmp or the env variable set in TMPDIR as the temp folder. To override this, I changed code locally to use the same temp folder I pass in to hicpro2juicebox.sh as an argument for sort
 `if [[ ! -z $RESFRAG ]]; then

    ## The restriction fragment sites file needs to be converted in order to be used in Juicebox command line tool (see attached script).
    ## They expect one line per chromosome with restriction sites separated by tabs and sorted by coordinate.
    ## Fix bug reported
    awk 'BEGIN{OFS="\t"; prev_chr=""}$1!=prev{print ""; prev=$1; printf "%s\t", $1} $1==prev {printf "%s\t",$3+1} END{print ""}' $RESFRAG | sed "s/\t\n/\n/" | sed "/^$/d" > ${TEMP}/$$_resfrag.juicebox
    ##awk 'BEGIN{OFS="\t"; prev_chr=""}$1!=prev{print ""; prev=$1; printf "%s\t", $1; printf "%s\t", $3} $1==prev{printf "%s\t",$3}END{print ""}' $RESFRAG | sed "s/\t\n/\n/" | sed "/^$/d" > ${TEMP}/$$_resfrag.juicebox

    ## The “pre” command needs the contact map to be sorted by chromosome and grouped so that all reads for one chromosome (let’s say, chr1) appear in the same column.
    ## Also, chromosomes should not have the ‘chr” substring and the strand is coded as 0 for positive and anything else for negative (in practice, 1).
    awk '{$4=$4!="+"; $7=$7!="+"; n1=split($9, frag1, "_"); n2=split($10, frag2, "_"); } $2<=$5{print $1, $4, $2, $3, frag1[n1], $7, $5, $6, frag2[n2], $11, $12 }$5<$2{ print $1, $7, $5, $6, frag2[3], $4, $2, $3, frag1[3], $12, $11}' $VALIDPAIRS | sort **-T ${TEMP}** -k3,3d  -k7,7d -S 90 > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted
else
    awk '{$4=$4!="+"; $7=$7!="+"} $2<=$5{print $1, $4, $2, $3, 0, $7, $5, $6, 1, $11, $12 }$5<$2{ print $1, $7, $5, $6, 0, $4, $2, $3, 1, $12, $11 }' $VALIDPAIRS | sort **-T ${TEMP}** -k3,3d  -k7,7d -S 90 > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted
fi` 
I am not sure this is universally acceptable solution.
Another solution is to set the TMPDIR env variable to some location that has enough space.

**Comment by nservant** [comment]
It does make sense. I will have a look to fix that in the next release.
Many thanks

**Comment by snikumbh** [comment]
@nservant FWIW, I just wanted to note that, the `hicpro2juicebox.sh` script could use the keyword `$JUICERJAR` instead of `$JUICEBOXJAR` to avoid a possible confusion, as these are two different jar files and the hicpro2juicebox shell script needs the `$JUICERJAR` here in order to run the `pre` command.

**Comment by nservant** [comment]
Indeed. I just fixed it in the devel branch of HiC-Pro. Will be pushed for the next release.
Thanks !

**Comment by nservant** [comment]
btw, I also included the changes proposed by @sowmyaiyer in the devel branch !
Thanks again for your suggestion.
