### ISSUE TITLE
What are the exact differences between the bwt2.validPairs file and .allValidPairs files?

### ISSUE THREAD

**Issue by ykai16** [nservant/HiC-Pro#226]
Hi Nico,

Could you please elaborate a bit on how the allValidPairs file is different from the bwt2.validPairs file in the data folder? The manual says allValidPairs file removes the duplicates from the bwt2.validPairs file. Is this the only difference between the two files?

I am analyzing a Hi-ChIP dataset, if I want to generate a BEDPE file for calling significant loops, should I use the bwt2.validPairs file or the .allValidPairs file? Thanks!

Best,
Yan

**Comment by nservant** [comment]
Hi Yan,
Basically, in output, you will have one .validPairs per fastq files.
It means that if you split your input data into 100 smaller chuncks to speed up the processing, HiC-Pro will generate one validPairs file per fastq.
Then, data are merged per sample (ie. input folder) to generate one allValidPairs file. 
When the merge is running, duplicates can be removed if specified in the config. Otherwise, the allValid will simply be the concatenation of all .validPairs file.

If you did not split your fastq file, the difference between the validPairs and AllvalidPairs file should only be the duplicates.

is that better ?
Best

**Comment by ykai16** [comment]
Thanks a lot for your prompt reply! This resolves my questions. Thanks :)

**Comment by ykai16** [comment]
Thanks a lot for your prompt reply! This resolves my questions. Thanks :)
