### ISSUE TITLE
error : Empty correlation matrix

### ISSUE THREAD

**Issue by QianzhaoJ** [nservant/HiC-Pro#233]
Hi :
When I used **HiTC** for calling A/B compartment，just like
`hic_part=hic$chr1chr1`
`pca.hic(hic_part, normPerExpected=TRUE,method="mean",npc=2)`
some errors occured:

> Estimate expected using mean contact frequency per genomic distance ...
Discard 2493 'x' intervals
Discard 2493 'y' intervals
NULL
Warning messages:
1: In max(diag(xdata), na.rm = FALSE) :
  no non-missing arguments to max; returning -Inf
2: In pca.hic(hic_part, normPerExpected = TRUE, method = "mean", npc = 2) :
  Empty correlation matrix for chr1

But when I used `method=loess` , it worked for the time being .But when
`hic_part=hic$chr9chr9`
`pca.hic(hic_part, normPerExpected=TRUE,method="loess",npc=2)`
these errors occured again 

> Lowess fit ...
Discard 307 'x' intervals
Discard 307 'y' intervals
NULL
Warning messages:
1: In getExpectedCounts(forceSymmetric(x), asList = TRUE, ...) :
  Contact map looks big. Use mean method instead or be sure that the loess fit gives good results.
2: In pca.hic(hic_part, normPerExpected = TRUE, method = "loess", npc = 2) :
  Empty correlation matrix for chr9

Many thanks！

**Comment by nservant** [comment]
Hi
Any chance to share with me the `hic_part` object ?
I think that it could come from empty values ...
Thanks
N

**Comment by QianzhaoJ** [comment]
Sure !
I have uploaded the **hic.matrix** file and **hic.bed** file to **OneDrive**
This is download link [https://1drv.ms/f/s!Av0xFmJ8bMfqlg06awK5zSXD7JOP](url)
and
`hic=importC(hic.matrix,hic.bed)`
`hic_part=hic$chr1chr1`

Thanks for your time !

**Comment by nservant** [comment]
Hi,
Very interesting question ! It took a few hours but I finally understood.
Tell me if I'm wrong but I think you normalized the data using ICE **per chromosome** ??

ICE makes the columns/rows of the output matrix equal to a constant.
The point here is that when we calculate the expected matrix, we usually first discard the raws/cols of the matrix with the lowest signal (sum of counts) ... the issue is that here all rows/cols have the same sums.
So they are all discarded .. and it crashes.
If you look at the message
```
Discard 2493 'x' intervals
Discard 2493 'y' intervals
```
This is the exact dimension of your chr1. So all rows/cols are discarded.
To fix this, you can run

```
pca.hic(hic_part, normPerExpected=TRUE,method="mean",npc=2, filter.low=NA)

```

However, the underlying question is more about the data normalization.
ICE was developed to be run at the genome-wide level. In this context, the sum of rows/cols are equal genome-wide, but not at the level of a chromosome.
So is that correct to run ICE chromosome-wide ?? I think that it's always a matter of assumption. If you think that the assumption of equal visibility is true at the chromosome level, you can go ahead. Otherwise, it is better to run it genome-wide.
Hope it helps
Nicolas

**Comment by QianzhaoJ** [comment]
Hi Nicolas
   Thanks for your time !!!
   I don't think I normalized the data using ICE **per chromosome** . But I have  randomly sampled a given number of cis-interactions from ValidPairs ,because I had many samples which had different sequencing depth and I want to eliminate the possible effects on data analyses of variable sequencing depths as described in doi:10.1038/nature23263 .
   After I extracted cis-interactions from ValidPairs ,I run HiC-pro again for building contact maps and ICE,
just like `$hicpro -i $input -o $output -c $config -s build_contact_maps -s ice_norm` . It will normalized the data using ICE **per chromosome** ?
   Another question is why `pca.hic` didn't work when I used 'mean' while it worked when I used 'loess' for `hic_part=hic$chr1chr1` ，and when I used 'loess', I can look at the message

> Lowess fit ...
Discard 269 'x' intervals
Discard 269 'y' intervals

Anyway, thank you very much !
Qianzhao

**Comment by nservant** [comment]
Hi,
"After I extracted cis-interactions from ValidPairs ,I run HiC-pro again for building contact maps"
So finally, even if you run ICE genome-wide, as you selected cis-interactions only, it is exactly as running ICE per chromosome.
'mean' and 'loess' are two different functions, so I'm not surprised that the behavior is a bit different.
From my experience, the 'loess' function usually have some difficulties to converge on high resolution Hi-C data ... that's why I would recommand to use the 'mean'
Best
Nicolas
