### ISSUE TITLE
Allowing multimapping reads

### ISSUE THREAD

**Issue by abhisheksinghnl** [nservant/HiC-Pro#234]
Hi,

I have a polyploidy genome from plant on which Hi-C experiment was performed.

My question is, does Hi-C pro allows multimapping reads? 

The other tools like hicexplorer discard my multimapping reads and that is not ideal for my analysis.

Thank you

**Comment by nservant** [comment]
Hi,
Yes it does since the last version.
HiC-Pro is using the bowtie2 mapper which randomly report one position in case on multiple mapping sites.
If you set RM_MULTI = 1, these reads are discarded.
But if you set RM_MULTI = 0, they are kept and therefore used to build the contact maps.

Note that this solution is not perfect, as bowtie2 chooses a random position (among all the good ones) on the genome. For instance, a more sophisticated approach could be to choose the read1/read2 position which are the closest ... and therefore more likely to be ligated together.
But even if this is not perfect, it should allow you to move a bit on the repeats issue.
All the best
N
