### ISSUE TITLE
bowtie local error

### ISSUE THREAD

**Issue by Antony-1996** [nservant/HiC-Pro#249]
hello author 
I encounter the bowtie2 alignment local error,while running HiC-Pro ,
![image](https://user-images.githubusercontent.com/43497334/57749906-9d149800-7712-11e9-89a0-30dd274004f1.png)and I am pretty sure file name contain zero keywords ,could it be something wrong with the bowtie2 version? because my bowtie2 version is 2.2.1.

**Comment by nservant** [comment]
Hi,
Did you look at the bowtie2.log file. I would expect a index error ...
N

**Comment by ViriatoII** [comment]
I had the same problem and here are the log files:
 $ cat test.bwt2glob.unmap_readsTrimming.log
```
/gpfs/project/projects/qggp/src/HiC-Pro_2.11.1/scripts/cutsite_trimming: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /gpfs/project/projects/qggp/src/HiC-Pro_2.11.1/scripts/cutsite_trimming)
/gpfs/project/projects/qggp/src/HiC-Pro_2.11.1/scripts/cutsite_trimming: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /gpfs/project/projects/qggp/src/HiC-Pro_2.11.1/scripts/cutsite_trimming)
```
C libraries missing. The problem is that your automatically created scripts (HiCPro_step1_.sh) don't load the modules that are dependencies (even though I had to specify it in a configure file in the installation folder...) 

I had to add it manually:
module load Bowtie2 SamTools/1.6 R/3.3.2  Python/2.7.5 gcc/8.1.0
