### ISSUE TITLE
Support for raw sequences coming in one file

### ISSUE THREAD

**Issue by rmurray2** [nservant/HiC-Pro#30]
It appears that HiC-Pro only supports reading raw sequences in which the reads (e.g. R1, R2) come in separate files; are there any plans to support cases in which the sequences from the left and right are combined and in one file or is there some option I'm missing?

**Comment by nservant** [comment]
Hi.
HiC-Pro does not support fastq file with merge R1 and R2 reads.
For Hi-C data analysis, R1 and R2 reads have to be mapped independently.
That's why HiC-Pro requires two input fastq files. In addition, this is the standard for Illumina PE data, you usually have two fast files as output of the sequencers.
N
