### ISSUE TITLE
convert iced matrix to cool

### ISSUE THREAD

**Issue by biohubx** [nservant/HiC-Pro#337]

**Comment by nservant** [comment]
Hi,
yes, this is because you try to convert iced normalized matrix.
Two solutions :
- either you convert raw matrix, asking cooler to normalize the data (`-norm`) option. Basically, it uses the same approach than HiC-Pro, so the maps should be very similar.
- Or you will have to update your cooler package. This small bug was fixed in the latest version of cooler
Best

**Comment by nservant** [comment]
implemented in 3.0.0

**Comment by Nuturetree** [comment]
Hi BioEpi and nservant:
  Can you told me how using the cooler convert the iced matrix to cool?  I not find the convert order.
Best
Nuturetree
