### ISSUE TITLE
--help option should "work" (and output the same thing as -h)

### ISSUE THREAD

**Issue by NelleV** [nservant/HiC-Pro#4]

**Comment by nservant** [comment]
Fixed in v2.4.0
All options can now be used as long or short form.
 -i|--input INPUT : input data folder; Must contains a folder per samples with fastq files
   -o|--output OUTPUT : output folder
   -c|--conf CONFIG : configuration file for Hi-C processing
   [-p|--parallel] : if specified run HiC-Pro in PBS/Torque mode
   [-s|--step ANALYSIS_STEP] : run only a subset of the HiC-Pro workflow; if not specified the complete workflow is run
      mapping: perform reads alignment
      proc_hic: perform Hi-C filtering
      build_raw_maps: build raw contact maps
      ice_norm : run ICE normalization on contact maps
   [-h|--help HELP]: help
