### ISSUE TITLE
Typo in Quick Start Guide and Feature Request 

### ISSUE THREAD

**Issue by rantingswede373** [nservant/HiC-Pro#46]
I came across this typo in the quick start guide example section. Maybe it was from an earlier version but the final normalization step points to a script that doesn't exist in 2.7.7

> lundi 2 mars 2015, 17:03:57 (UTC+0100)
> Run ICE Normalization ...
> normContactMaps.sh -c /bioinfo/users/nservant/projects_dev/HiC-Pro/config_test.txt >> hicpro_IRM90_rep1_split.log

I think it should be running the ice_norm.sh from the scripts directory.

Secondly, I was wondering if you had any plans to include A/B Compartment calling from a PCA analysis eigenvector. This is similar to the doCisPCADomains function in hiclib (http://mirnylab.bitbucket.org/hiclib/binneddata.html#hiclib.binnedData.binnedData.doCisPCADomains).

Thanks for publishing such a well-written and documented pipeline! Really great stuff!

**Comment by nservant** [comment]
Yes indeed the logs are from an old version of HiC-Pro, I will update it. Thank you.
Regarding the chromosome compartment calling, we do not plan to add such function in HiC-Pro which is really dedicated to the data processing.
However, I develop since a couple of years a R/Bioconductor package (HiTC).
HiTC is compatible with HiC-Pro. Look at the importC function to lead the contact maps into R.
Then, this package provides several functions for downstream analysis including the compartment calling. Look at the pca.hic function. I suggest to use the latest version of HiTC because I released the code for chromosome compartment calling a few months ago
And if you have any question, do not hesitate the contact me.
Thanks !

**Comment by rantingswede373** [comment]
That sounds like a good plan to me. I like the idea of having a very straightforward analysis pipeline that connects well with other packages depending on the users needs. I've been shopping around for downstream analysis packages and it seems like HiTC would be the way to go.

Thanks again!
