### ISSUE TITLE
make: *** [/HiC-Pro_3.0.0/bin/../scripts//Makefile:144: bowtie_pairing] Error 1

### ISSUE THREAD

**Issue by ld9866** [nservant/HiC-Pro#470]
Hello! l am using the docker version hic-pro, but l find it is hard for me because the step "Pairing of R1 and R2 tags ..." is always wrong, can you tell me how to solve this problem?
Thank you！

Run HiC-Pro 3.0.0
--------------------------------------------
Mon Aug 16 14:31:19 UTC 2021
Bowtie2 alignment step1 ...
Logs: logs/rawdata/mapping_step1.log

--------------------------------------------
Tue Aug 17 09:46:26 UTC 2021
Bowtie2 alignment step2 ...
Logs: logs/rawdata/mapping_step2.log

--------------------------------------------
Tue Aug 17 15:22:47 UTC 2021
Combine R1/R2 alignment files ...
Logs: logs/rawdata/mapping_combine.log

--------------------------------------------
Tue Aug 17 17:33:15 UTC 2021
Mapping statistics for R1 and R2 tags ...
Logs: logs/rawdata/mapping_stats.log

--------------------------------------------
Tue Aug 17 18:26:20 UTC 2021
Pairing of R1 and R2 tags ...
Logs: logs/rawdata/mergeSAM.log
make: *** [/HiC-Pro_3.0.0/bin/../scripts//Makefile:144: bowtie_pairing] Error 1

**Comment by jacomegutierrez** [comment]
Hello, 
I have the same error, in the mergeSAM.log file says "Forward and reverse reads not paired. Check that BAM files have the same read names and are sorted."
How can I fix it? apparently my fastq files are ok.

**Comment by ld9866** [comment]
Dear jacomegutierrez:

**Comment by KurotakiDaisuke** [comment]
Hello,
I am using conda HiC-pro 3.1.0. I have the same error.
I prefer to use the HiC-pro instead of other software. 
Is there any solution to this problem?
Thanks!

--------------------
Pairing of R1 and R2 tags ...
Logs: logs/sample1/mergeSAM.log
make: *** [/root/HiC-Pro/bin/../scripts//Makefile:144: bowtie_pairing] Error 1

/HiC-Pro_3.1.0/scripts/mergeSAM.py -q 10 -t -v -f bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam -r bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam -o bowtie_results/bwt2/sample1/SKK1_combined_q_genome.bwt2pairs.bam
[E::idx_find_and_load] Could not retrieve index file for 'bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam'
## mergeBAM.py
## forward= bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam
## reverse= bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam
## output= bowtie_results/bwt2/sample1/SKK1_combined_q_genome.bwt2pairs.bam
## min mapq= 10
## report_single= False
## report_multi= False
## verbose= True
## Merging forward and reverse tags ...
Forward and reverse reads not paired. Check that BAM files have the same read names and are sorted.

**Comment by ld9866** [comment]
> 您好， 我正在使用 conda HiC-pro 3.1.0。我遇到了同样的错误。 我更喜欢使用 HiC-pro 而不是其他软件。 这个问题有解决办法吗？ 谢谢！
> 
> R1 和 R2 标签配对... 日志：logs/sample1/mergeSAM.log make：*** [/root/HiC-Pro/bin/../scripts//Makefile:144: bowtie_pairing] 错误 1
> 
> /HiC-Pro_3.1.0/scripts/mergeSAM.py -q 10 -t -v -f bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam -r bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam -o bowtie_results/bwt2/sample1/SKK1_combined_q_genome.bwt2pairs.bam [E::idx_find_and_load] 无法检索“bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam”的索引文件 [E::idx_find_and_load] 无法检索'bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam'
> 
> ## 合并BAM.py
> ## 转发= bowtie_results/bwt2/sample1/SKK1_combined_q_R1_genome.bwt2merged.bam
> ## 反向= bowtie_results/bwt2/sample1/SKK1_combined_q_R2_genome.bwt2merged.bam
> ## 输出 = bowtie_results/bwt2/sample1/SKK1_combined_q_genome.bwt2pairs.bam
> ## 最小 mapq= 10
> ## report_single=False
> ## report_multi = False
> ## 详细=真
> ## 合并正向和反向标签...
> 正向和反向读取不成对。请检查 BAM 文件是否具有相同的读取名称并且已排序。

You could try juicer first, or use some example data to try to know whether the data is ok

**Comment by KurotakiDaisuke** [comment]
Thanks! I have already analyzed the same fastq files using Juicer and successfully obtained output files such as .hic files.

**Comment by ld9866** [comment]
OK

**Comment by KurotakiDaisuke** [comment]
Can I convert Juicer .hic files to validPairs files?
Thanks for your help!
