### ISSUE TITLE
Is there any solution about using DdeI in HiC-PRO?

### ISSUE THREAD

**Issue by khsjh** [nservant/HiC-Pro#601]
Hi, I want to know how can I use HiC-PRO for my data which use DdeI in Hi-C.
I think I should make genome digestion file for this data, but I don't know how can I build the digestion file and where to modify the scripts.
The DdeI restrioction site is

![image](https://github.com/nservant/HiC-Pro/assets/109505999/b6fab0bc-411d-40eb-a5d7-51c381a0f83d)

In digestion_genome.py, the 'N' sequence was used.
The restriction enzymes what I used is DpnII and DdeI.
Then, the restriction site would be GATCGATC, GATCTNAG, CTNAGATC, CTNATNAG

Is it right?

**Comment by nservant** [comment]
look good indeed. Did you try ?

**Comment by yishengys** [comment]
Have you solved this problem?

**Comment by nservant** [comment]
You can just specify your own restriction motif in the config file

**Comment by yishengys** [comment]
Thank you for your assistance. In my recent Hi-C experiment, I used DdeI as the restriction enzyme, setting the restriction site as "C^TNAG" in the digestion_genome.py analysis. However, I'm uncertain if this was the correct approach. My HiC-Pro Quality Control results show that 93.4% of all pairs were classified as invalid, with 70.9% being dangling end pairs.

I'm a beginner in this field, and the results I've obtained differ significantly from what I expected based on similar studies. Despite following the standard protocol closely, the outcome doesn't align with my expectations. I'm unsure whether these discrepancies are due to issues in the analysis process or if there might have been an error during the earlier sample preparation stages.

I would greatly appreciate any insights or guidance you could offer to help me understand and resolve this issue.
![ce6a20c9b21583ae3420a0e52cfe916](https://github.com/user-attachments/assets/19396076-031c-4b40-9240-3d208cc154a7)
![228e4ec7673fabcff0eeec52149d9b1](https://github.com/user-attachments/assets/88ae5d47-87fe-488f-9102-37c159d4d3b6)

**Comment by nservant** [comment]
Did you also adjust the LIGATION_SITE in the config file ?
Another idea would be to run HiC-Pro in dnase mode (without using the restriction enzyme information) adding a MIN_CIST distance of 1000. It means that all read pairs with a distance lower than 1000 will be removed. In practice, it usually means removing most of the dangling-end pairs. Although the mapping percentage could be lower in this mode, it will at least help you to confirm the quality of your library.
If you have a lot a reads discarded because too close to each other (dangling end), it is likely that the ligation step of your protocol failed.

**Comment by yishengys** [comment]
Thanks for your reply. I have checked the config file , the LIGATION_SITE in my process is "CTNAGGANTC". I don't know if it's right. I will run this process as your advice . Thank you very much !

**Comment by ahmedabbas811** [comment]
Hello,

Did you solve the issue and know what is the Ligation site for DpnII and DdeI?
I am having trouble concerning the same issue.

If possible, can you please send an example of config file with all entries filled properly?
I think I cannot run the method accurately.

Thanks
Ahmed

**Comment by khsjh** [comment]
I don't remember exactly because it was a long time ago, but if I remember correctly, I think I considered all possible restriction sites.
