### ISSUE TITLE
Error in ICE Normalization

### ISSUE THREAD

**Issue by smarhon** [nservant/HiC-Pro#70]
Hi 
I am getting this error at the ICE normalization stage. Do you have any idea about this?

Thanks
Sajid

Traceback (most recent call last):
  File "/home/marhon/HiC-Pro_2.7.7/scripts/ice", line 90, in <module>
    verbose=args.verbose, eps=args.eps)
  File "/usr/local/lib/python2.7/dist-packages/iced/normalization.py", line 60, in ICE_normalization
    is_symetric_or_tri(X)
  File "/usr/local/lib/python2.7/dist-packages/iced/utils/validation.py", line 13, in is_symetric_or_tri
    raise ValueError("The matrix should be symmetric")
ValueError: The matrix should be symmetric
make: *** [ice_norm] Error 1

**Comment by nservant** [comment]
Hi,
You could please tell me which HiC-Pro version are you using ?
as well as which iced python version (iced.__version__) ?
And finally, which parameter you put in the configuration file for the ICE parameter ?
Thank you
Nicolas

**Comment by smarhon** [comment]
Hi Nicolas

I use HiC-Pro_2.7.7.

I checked the version of ICED package. It says 0.1-git.

The parameters I am using are:

MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

Thanks
Sajid

**Comment by nservant** [comment]
humm .. what did you put in MATRIX_FORMAT ?

**Comment by smarhon** [comment]
I put upper

**Comment by nservant** [comment]
! Could you please check in the matrix file if the first column is always >= second column ?
This should be the case ...

**Comment by smarhon** [comment]
In the raw matrix, the first column is <= the second column (not >=).

**Comment by nservant** [comment]
ok, so it means that the matrix is symmetric. Could you please update the iced package version ?
You can find a more recent version in scripts/src/
Then, you can just rerun the normalization using -s ice_norm (-i should be the matrix folder)
Thanks

**Comment by nservant** [comment]
Hi
Did you fix your issue ?

**Comment by smarhon** [comment]
Hi Nicholas
Thanks for asking. 
I updated the ice package but the problem is still there. I am having this problem when I process the GM12878 cell line for the files of the MboI enzyme.  Everything is ok until I try to normalize the raw matrix. 

Thanks
Sajid

**Comment by nservant** [comment]
This is strange. Who do you mind sending me one matrix file please ? at high resolution, like 1Mb ?
N

**Comment by ilyco** [comment]
I got the same error but then figured out my raw matrices were incomplete from a certain resolution onwards. I ran build contact maps again on those matrices and then it worked with no problems.

**Comment by richgill8** [comment]
Hi Nicholas I also encountered this issue while trying to process the GM12878 MboI data downloaded from the SRA. Re-running the pipeline, as suggested in the 2/13 comment, did not resolve the issue. Please advise.

Thanks,
Richard

**Comment by Edahi** [comment]
Hi Nicholas, 
I an running IMR90 samples also with MboI. unfortunately I also have the same problem as commented above, ICE norm not working. I pasted below the whole thing, my code and the output as is:
Hope it helps! This problem is not solved yet.

`+ /home/edahi/download/code/HiC-Pro-master_py2.7/bin/HiC-Pro -c /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt -i /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hic_results/data/ -o /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC -s build_contact_maps

Run HiC-Pro 2.9.0
make: Warning: File `/mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt' has modification time 69 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
make: Warning: File `/mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt' has modification time 69 s in the future
--------------------------------------------
Tue Jan 23 10:40:04 PST 2018
Generate binned matrix files ...
/home/edahi/download/code/HiC-Pro-master_py2.7/scripts/build_raw_maps.sh -c /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt
make: warning:  Clock skew detected.  Your build may be incomplete.
+ /home/edahi/download/code/HiC-Pro-master_py2.7/bin/HiC-Pro -c /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt -i /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hic_results/matrix/ -o /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/ -s ice_norm

Run HiC-Pro 2.9.0
--------------------------------------------
Tue Jan 23 12:11:08 PST 2018
Run ICE Normalization ...
/home/edahi/download/code/HiC-Pro-master_py2.7/scripts/ice_norm.sh -c /mnt/BioAdHoc/Groups/RaoLab/BenjaminD/02.hmC_Method/02.Analysis/01.HiC-Pro/hg19_2.9.0/01.IMR90_Rao2014_Cell/IMR90_HIC/hg19_MboI_config.txt >> hicpro.log
/share/apps/python/python-2.7.13/lib/python2.7/site-packages/subprocess32.py:472: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/edahi/download/code/HiC-Pro-master_py2.7/scripts/ice", line 107, in <module>
    verbose=args.verbose, eps=args.eps, output_bias=True)
  File "/share/apps/python/python-2.7.13/lib/python2.7/site-packages/iced/normalization.py", line 66, in ICE_normalization
    is_symetric_or_tri(X)
  File "/share/apps/python/python-2.7.13/lib/python2.7/site-packages/iced/utils/validation.py", line 13, in is_symetric_or_tri
    raise ValueError("The matrix should be symmetric")
ValueError: The matrix should be symmetric
make: *** [ice_norm] Error 1
`

**Comment by realzhang** [comment]
Hi Nicholas,
same problem:

python /usr/local/bin/HiC-Pro_2.11.1/scripts/ice --results_filename lib1_25kb_iced.matrix --filter_low_counts_perc 0.05 --filter_high_counts_perc 0.02
 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --verbose 1 lib1_25kb.matrix.3.0.0
/usr/lib64/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Using iced version 0.5.8
Loading files...
Normalizing...
Filter 20299 out of 130625 bins ...
Traceback (most recent call last):
  File "/usr/local/bin/HiC-Pro_2.11.1/scripts/ice", line 106, in <module>
    verbose=args.verbose, eps=args.eps, output_bias=True)
  File "/usr/lib64/python2.7/site-packages/iced/normalization/__init__.py", line 66, in ICE_normalization
    is_symetric_or_tri(X)
  File "/usr/lib64/python2.7/site-packages/iced/utils/validation.py", line 13, in is_symetric_or_tri
    raise ValueError("The matrix should be symmetric")
ValueError: The matrix should be symmetric

Could you give some advice? Many thanks!

**Comment by realzhang** [comment]
This is the result of version 3.0.0:
python3 /usr/local/bin/HiC-Pro_3.0.0/scripts/ice --results_filename lib1_25kb_iced.matrix --filter_low_counts_perc 0.05 --filter_high_counts_perc 0.02 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --verbose 1 lib1_25kb.matrix.3.0.0
/home/zhang/miniconda3/lib/python3.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Using iced version 0.5.8
Loading files...
Traceback (most recent call last):
  File "/usr/local/bin/HiC-Pro_3.0.0/scripts/ice", line 73, in <module>
    i, j, data = loadtxt(filename).T
  File "/home/zhang/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1093, in loadtxt
    first_vals = split_line(first_line)
  File "/home/zhang/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1033, in split_line
    line = regex_comments.split(line, maxsplit=1)[0]
TypeError: expected string or bytes-like object

**Comment by think-o** [comment]
> usr/local/bin/HiC-Pro_3.0.0/scripts/ice --results_filename lib1_25kb_iced.matrix --filter_low_counts_perc 0.05 --filter_high_counts_perc 0.02 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --verbose 1 lib1_25kb.matrix.3.0.0

@realzhang I have got the same error while using the recent version of iced. But, when I have used the iced version "0.4.2" as mentioned in the README file of HiC-Pro_3.0.0. I did not get that error anymore. Do not know if this would be of much help. It has been a long time. This issue helped me to troubleshoot the problem. So thought of responding to this.
