### ISSUE TITLE
hicpro2juicebox.sh problem

### ISSUE THREAD

**Issue by yuzhang0327** [nservant/HiC-Pro#82]
Dear professor,

I tired to use this scripts with the validpair data generated by HiC-pro 2.7.8, the format of my valid pair looks like this:
HWI-D00489:178:C9EW9ANXX:6:2102:4028:64517      chr1    102     -       chr5    12240384        +       NA      NA      NA      42
HWI-D00489:178:C9EW9ANXX:6:1205:8357:58092      chr1    159     -       chr1    2393    -       NA      NA      NA      42      42
HWI-D00489:178:C9EW9ANXX:6:1205:20384:86780     chr1    173     -       chr5    130600140       +       NA      NA      NA      42

And the error is stated as below:
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.

So should I change any parameter for HiC-pro?

Best,
Yu

**Comment by nservant** [comment]
Hi Yu
I think there is something strange with your restriction fragment file.
Could you please show me the first line ? The 'NA' value should correspond to the name of restriction fragments.

Regarding hicpro2juicebox, could you give me the command you used please ?
Thank you

**Comment by liufuyan2016** [comment]
I also have the same issues:
command:
sh /share/nas30/liufuyan/HiC-Pro-master/HiC-Pro_2.8.1/bin/utils/hicpro2juicebox.sh -i hic_results/data/all/all_allValidPairs -g  /share/nas30/liufuyan/Project/AT/Interaction/QC/AT.fa.len -j  /share/nas1/liufuyan/juicer_tools_linux_0.8.jar -r ../digest_AT.fa.bed -o ./
all_allValidPairs :
HWI-ST1395:121:c3rc9acxx:8:1103:10192:142190	Chr1	52.5	+	Chr1	4412744.5	-	405	HIC_Chr1_1	HIC_Chr1_2476	37	37	
HWI-ST1395:121:c3rc9acxx:8:1105:13636:34912	Chr1	60.5	+	Chr3	12321155.5	-	440	HIC_Chr1_1	HIC_Chr3_6690	37	37	
HWI-ST1395:121:c3rc9acxx:8:1102:4320:163352	Chr1	61.5	+	Chr1	29133703.0	+	325	HIC_Chr1_1	HIC_Chr1_16262	37	37	
HWI-ST1395:121:c3rc9acxx:8:1102:3917:104192	Chr1	69.5	+	Chr1	5719117.5	-	526	HIC_Chr1_1	HIC_Chr1_3222	37	37	
HWI-ST1395:121:c3rc9acxx:8:1103:20373:65517	Chr1	69.5	+	Chr5	7816.0	-	333	HIC_Chr1_1	HIC_Chr5_5	37	37	
HWI-ST1395:121:c3rc9acxx:8:1102:12053:12722	Chr1	76.5	+	Chr1	10612809.5	-	382	HIC_Chr1_1	HIC_Chr1_5723	37	37	
HWI-ST1395:121:c3rc9acxx:8:1102:14477:61471	Chr1	87.5	+	Chr3	3024262.5	-	348	HIC_Chr1_1	HIC_Chr3_1670	37	37	
HWI-ST1395:121:c3rc9acxx:8:1101:16294:167960	Chr1	101.5	+	Chr4	17284646.0	+	301	HIC_Chr1_1	HIC_Chr4_10325	37	37	
HWI-ST1395:121:c3rc9acxx:8:1105:6145:118986	Chr1	108.5	+	Chr3	19325946.5	+	287	HIC_Chr1_1	HIC_Chr3_10340	37	37

**Comment by nservant** [comment]
Hi
I'm sure that this issue comes from discrepancies between your annotations files.
It can either come from the chromosome names for instance, or the names of restriction fragment.
So could you carrefully look at your three file ; all_allValidPairs + digest_AT.fa.bed + AT.fa.len, and check them.
For instance, I see that you put a capital "C" at Chr1, ... Is it the same in the other files ?
Best

**Comment by liufuyan2016** [comment]
the three  input file：
all_allValidPairs :
HWI-ST1395:121:c3rc9acxx:8:1103:10192:142190	Chr1	52.5	+	Chr1	4412744.5	-	405	HIC_Chr1_1 HIC_Chr1_2476	37	37
HWI-ST1395:121:c3rc9acxx:8:1105:13636:34912	Chr1	60.5	+	Chr3	12321155.5	-	440	HIC_Chr1_1 HIC_Chr3_6690	37	37
AT.fa.len：
Chr1 30427671
Chr2 19698289
Chr3 23459830
Chr4 18585056
Chr5 26975502
digest_AT.fa.bed 
Chr1	0	299	HIC_Chr1_1	0	+
Chr1	299	4100	HIC_Chr1_2	0	+
Chr1	4100	5098	HIC_Chr1_3	0	+
Chr1	5098	7826	HIC_Chr1_4	0	+
Chr1	7826	11399	HIC_Chr1_5	0	+
Chr1	11399	24993	HIC_Chr1_6	0	+
Chr1	24993	26462	HIC_Chr1_7	0	+
Chr1	26462	31377	HIC_Chr1_8	0	+

but an eeror occured：ava.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.

**Comment by nservant** [comment]
humm ... all files look good.
Could you send me these files on my personnal adress, so that I can have a try ?
thanks

**Comment by nservant** [comment]
Hi
Thanks for the data.
So actually, there are two issues ;
1- the chromosome length file must be tab-delimited
2- juicebox does not expect float values in the valid pairs file. In practice, we chose to put the middle position of the reads. As most of the project involved 100bp reads, I never had floating values before.
I'll fix that in the next release.
In the meantime, just run something like ;
awk '{$3=int($3);$6=int($6);print;}' all.validPairs > all.validPairs.mod 
Best
