### ISSUE TITLE
hicpro2juicebox resfrag file indexing problem

### ISSUE THREAD

**Issue by sf-nevermore** [nservant/HiC-Pro#95]
Hi,

I use the command
/usr/bin/HiC-Pro_2.7.9/bin/utils/hicpro2juicebox.sh -i Eos_output/hic_results/data/Eos/Eos_allValidPairs -r /usr/bin/HiC-Pro_2.7.9/annotation/mm9_MboI_resfrag.bed -o Eos.hicpro.hic -g mm9 -j /home/software/juicer_tools.1.7.5_linux_x64_jcuda.0.8
to transform validpair to juicebox hic files. However when I check the resfrag.juicebox file, I notice 2 problem:
the file looks like:
chr10   3000182 3000182 3000266 3001030 3001324 3002052 3003309 3003459 3003969....

P1: the first 2 coordinates are repeated

P2: when I compared the resfrag provided by juicebox (https://bcm.app.box.com/s/19807ji76uy20cd1wau9g146nypsv2u0)
chr10 3000183 3000267 3001031 3001325 3002053 3003310 3003460 3003970 
It seems hicpro using 0 indexing and juicebox use 1 indexing?

Thanks

**Comment by nservant** [comment]
Hi,
Thanks for the comments. I will check that and come back to you.
Do you know if it generates any error ?

**Comment by sf-nevermore** [comment]
Yes. It generates error in the juicebox pre step

Problem with creating fragment-delimited maps, NullPointerException.
This could be due to a null fragment map or to a mismatch in the chromosome name in the fragment map vis-a-vis the input file or chrom.sizes file.
Exiting.

I tried both resfrag files and give the chrom.sizes file, but they all gave same error.

**Comment by nservant** [comment]
Hi,
I just fix these bugs in the devel branch
https://github.com/nservant/HiC-Pro/tree/devel
Could you please make a test ?
You can simply download the hicpro2juicebox.sh script and put it in bin/utils/
Many thanks
N

**Comment by sf-nevermore** [comment]
Thanks, I tested. It can generate the .hic files but I need to remove  chr in the chromosome names in the resfrag file. It is the issue of juicetools, I am asking the developer and will get back to you.

Besides that I have several suggestions:
1. the reads coordinates should be modified to 1-based to make the .hic file, not only for the resfrag?
2. since many hic dataset are large, sorting will be very slow. I manually change the -S size and add --parallel option to the sort command to speedup. I think it might be worthwhile to add these options.

**Comment by nservant** [comment]
Besides that I have several suggestions:
1. the reads coordinates should be modified to 1-based to make the .hic file, not only for the resfrag?

Yes, I have to double check that. As the reads coordinates are extracted from the BAM file, they might be 1-based, whereas the resfrag coordinates were extracted from the BED file (0-based) ... but I will check that. 

2. since many hic dataset are large, sorting will be very slow. I manually change the -S size and add --parallel option to the sort command to speedup. I think it might be worthwhile to add these options.

Sorry, where do you put these options ?
Thank again for your help !

**Comment by sf-nevermore** [comment]
Thank you for checking. 
I put the parameter in the 2 sort commands.
![image](https://user-images.githubusercontent.com/7236497/29840165-e124edfe-8cb5-11e7-98c2-8c314c21aa80.png)

The developer said they are currently fixing the chromosome naming issue.  Might need to wait for next version release.

Thanks

**Comment by nservant** [comment]
Hi,
I close the issue. The 1-based coordinates are fixed in current devel version 2.10.0
Regarding sort --parallel, although it looks very interested, it is not supported on several os including debian for instance. So for the moment, I will not change it, but keep it in mind !
Thanks again

**Comment by liufuyan2016** [comment]
The error also appeared:
Problem with creating fragment-delimited maps, NullPointerException.
This could be due to a null fragment map or to a mismatch in the chromosome name in the fragment map vis-a-vis the input file or chrom.sizes file.

How to dela with it? I use the suggestion below,but the error is not avoid.

**Comment by sf-nevermore** [comment]
If you really need the fragment maps rather than fix-length bins, you can try to remove the chr in the resfrag file.
Like the follow for chr10
10 3000182 3000182 3000266 3001030 3001324 3002052 3003309 3003459 3003969....

**Comment by nservant** [comment]
Hi guys,
Yes It depends if you provide your own chrom_size files or if you just specified the organism, for instance hg19, mm9. If you specify the genome name, Juicebox will use its own annotation, and therefore you need to have the same type of input file (i.e. removing the "chr" as proposed by sf-nevermore) can help.
N
