### ISSUE TITLE
Error in HiC-pro quality check 

### ISSUE THREAD

**Issue by souryacs** [nservant/HiC-Pro#98]
Hi,

When applying HiC-pro pipeline (version 2.7.8) on a pair of fastq reads, I am getting the following error:
make: *** [hic_qc] Error 1

Inspecting within the "HiCPro/logs/" directory, I found the following error in the file "plot_hic_contacts.Rout":
Error: cis_sr + cis_lr == cis_inter is not TRUE

Can someone please help me in finding what exactly I am doing wrong?
Thanks.

~Sourya

**Comment by nservant** [comment]
Hi Sourya,
Could you give me more information ;
- Organization of your data 
- Command line
- Outputs ?

My feeling is that there is something wrong in the data organization.
Best

**Comment by DonStephano** [comment]
Hi,
has someone figured out what's wrong? I'm getting a similar error when using HiC-Pro with our own data (small subset, around 2.5M reads).

`Di 17. Okt 10:06:56 CEST 2017
Run quality checks for all samples ...
/home/user/bin/HiC-Pro_2.9.0/scripts/make_plots.sh -c /media/daten/user/HiC-Pro/config -p "all" >> hicpro.log
make: *** [hic_qc] Error 1`
[plot_mapping_portion.txt](https://github.com/nservant/HiC-Pro/files/1390534/plot_mapping_portion.txt)

Thx for for any help.
Steph

**Comment by nservant** [comment]
Hi,
The error is not due to R itself, but should be in the mapping step.
Could you show me how you organize your data ? thanks

**Comment by DonStephano** [comment]
Hi Nicola,
thank you very much for your quick reply and help. 
Could it be, that the error occurs after mapping? I see following:

`Mi 18. Okt 15:29:55 CEST 2017
Combine both alignment ...
/home/user/bin/HiC-Pro_2.9.0/scripts/bowtie_combine.sh -c /media/daten/user/HiC-Pro/config.txt >> hicpro.log
mv: cannot stat ‘bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.sorted.bam’: No such file or directory
mv: cannot stat ‘bowtie_results/bwt2/Dixon2M/SRR400264_00_R2_hg19.bwt2merged.sorted.bam’: No such file or directory
`
I guess the bam files should be sorted prior of merging?! I suspect that something is not correct concerning samtools although samtools is installed and properly working.

Organization of the data should be correct. I organized it as described in the manual. The error occured using our own data and the Dixon testdata.

Thx
Stephan

**Comment by nservant** [comment]
Yes indeed. Which samtools version are you using. Someone recently reported an issue in samtools sort on some system (order of parameters).
Would you have any chance to try the current devel version ?
https://github.com/nservant/HiC-Pro/tree/devel
Thanks

**Comment by DonStephano** [comment]
Ah ok, we're using samtools 1.3.
I'll try the devel version and let you know the results.
Thx a lot

**Comment by DonStephano** [comment]
Hi @nservant!

I have two problems with the recent version:
```
> HiC-Pro --version
HiC-Pro version 2.10.0
```

It seems that a few commands are executed twice:

```Combine bowtie_results/bwt2_global/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.bam and bowtie_results/bwt2_global/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.bam files ...
Dixon2M/SRR400264_00_R1_hg19
Dixon2M/SRR400264_00_R1_hg19
/home/gilsbach/bin/samtools merge -@ 25 -n -f bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam bowtie_results/bwt2_global/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.bam bowtie_results/bwt2_local/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.unmap_bwt2loc.bam
/home/gilsbach/bin/samtools merge -@ 25 -n -f bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam bowtie_results/bwt2_global/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.bam bowtie_results/bwt2_local/Dixon2M/SRR400264_00_R1_hg19.bwt2glob.unmap_bwt2loc.bam
/home/gilsbach/bin/samtools sort -@ 25 -n -T tmp/SRR400264_00_R1_hg19 -o bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.sorted.bam bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam
/home/gilsbach/bin/samtools sort -@ 25 -n -T tmp/SRR400264_00_R1_hg19 -o bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.sorted.bam bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam
mv bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.sorted.bam bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam
mv bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.sorted.bam bowtie_results/bwt2/Dixon2M/SRR400264_00_R1_hg19.bwt2merged.bam
-----------------
```

Which yields to an error for the seconda `mv`.
The other error is:
```
make: *** [mapped_2hic_fragments] Error 1
```

It would be handy if I could see actual the real error message in the log file.
Thanks,
Don

**Comment by nservant** [comment]
Hi,
That's very strange. Could you show me the content of your input folder ?
Are you sure that you do not have twice the same files ?
Best

**Comment by nservant** [comment]
Do you still have your issue ?

**Comment by souryacs** [comment]
Hi Nicholas, 

Sorry for the late reply. I have managed to solve the issue. Considering a HiChIP data with MboI restriction enzyme based cutting, I had to set the configuration file as:

LIGATION_SITE = GATCGATC
MIN_FRAG_SIZE = #100  
MAX_FRAG_SIZE = #100000 
MIN_INSERT_SIZE = #50
MAX_INSERT_SIZE = #600  

Basically, I have omitted any value of the fragment size parameters, and relied on the default settings of HiC-pro. Then, there was no problem. I am using HiC-pro version 2.9.0.

**Comment by xiaorenwu1111** [comment]
Dear Nicholas,
I met the same error when I used the tes data to hic-pro pipeline.
The error followed.
Fri Oct 18 17:36:39 CST 2019
Run quality checks for all samples ...
Logs: logs/dixon_2M/make_Rplots.log
make: *** [hic_qc] Error 1

And the logs file like this:
##Quality checks - Mapping results ...
/data/users/robots/software/R_Bioconductor/R_Bioconductor-3.4.2/bin/R CMD BATCH --no-save --no-restore "--args picDir='hic_results/pic/dixon_2M' bwtDir='bowtie_results/bwt2/dixon_2M' sampleName='dixon_2M' r1tag='SRR400264_00_R1.fastq.gz' r2tag='SRR400264_00_R2.fastq.gz'" /data/users/liyufang/software/Hi-C/HiC-Pro_2.11.1/scripts/plot_mapping_portion.R logs/dixon_2M/plot_mapping_portion.Rout

I can't solve this problem. Can you help me ? Thank you !

**Comment by nservant** [comment]
Hi,
What do you have in the plot_mapping_portion.Rout file ?
Thanks

**Comment by cmonat** [comment]
Hi Nicolas,
I got a similar error on my data.
The slurm.log file look like this:
`--------------------------------------------
ven. mai 29 02:39:00 CEST 2020
Merge chunks from the same sample ...
Logs: logs_Rn_v8p_bis/sample5/merge_valid_interactions.log
Logs: logs_Rn_v8p_bis/sample6/merge_valid_interactions.log
Logs: logs_Rn_v8p_bis/sample7/merge_valid_interactions.log
Logs: logs_Rn_v8p_bis/sample8/merge_valid_interactions.log

--------------------------------------------
ven. mai 29 03:18:23 CEST 2020
Merge stat files per sample ...
Logs: logs_Rn_v8p_bis/sample5/merge_stats.log
Logs: logs_Rn_v8p_bis/sample6/merge_stats.log
Logs: logs_Rn_v8p_bis/sample7/merge_stats.log
Logs: logs_Rn_v8p_bis/sample8/merge_stats.log

--------------------------------------------
ven. mai 29 03:18:27 CEST 2020
Generate binned matrix files ...
Logs: logs_Rn_v8p_bis/sample5/build_raw_maps.log
Logs: logs_Rn_v8p_bis/sample6/build_raw_maps.log
Logs: logs_Rn_v8p_bis/sample7/build_raw_maps.log
Logs: logs_Rn_v8p_bis/sample8/build_raw_maps.log

--------------------------------------------
ven. mai 29 03:27:04 CEST 2020
Run quality checks for all samples ...
Logs: logs_Rn_v8p_bis/sample5/make_Rplots.log
make: *** [hic_qc] Erreur 1
slurm-29980059.out (END)`

The log look like this:
`##Quality checks - Mapping results ...
/opt/apps/gcc-8.1.0/R-3.5.1/bin/R CMD BATCH --no-save --no-restore "--args picDir='hic_results_Rn_v8p_bis/pic/sample5' bwtDir='bowtie_results_Rn_v8p_bis/bwt2/sample5' s
ampleName='sample5' r1tag='_R1' r2tag='_R2'" /storage/groups/gdec/bin/tools/hic-pro/HiC-Pro-2.11.1/HiC-Pro_2.11.1/scripts/plot_mapping_portion.R logs_Rn_v8p_bis/sample5
/plot_mapping_portion.Rout
logs_Rn_v8p_bis/sample5/make_Rplots.log (END)`

And the end of plot_mapping_portion.Rout is:
`> ## Make plots
> mat_r1 <- getMapMat(stats_per_sample_r1[1], stats_per_sample_r1[2], stats_per_sample_r1[3], stats_per_sample_r1[4])
> mat_r1$lab <- factor(mat_r1$lab, levels=c("n.un","n.loc","n.glob","n.map"))
> p1 <- ploMapStat(mat_r1, sampleName=sampleName, tag="R1")
Loading required package: RColorBrewer
Loading required package: ggplot2
Loading required package: grid
Error in brewer.pal(6, "Blues") :
  impossible de trouver la fonction "brewer.pal"
Calls: ploMapStat
De plus : Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘RColorBrewer’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggplot2’
Exécution arrêtée
(END)`

If I understood well it's due to missing packages of ggplot2 and RColorBrewer, how can I change that? Should I add them directly in my slurm command line? 
Thank you very much
Have a great day
Cheers
C.

**Comment by nservant** [comment]
Hi
You should install the missing packages first please ... in your R at  /opt/apps/gcc-8.1.0/R-3.5.1/bin/R
Cheers

**Comment by cmonat** [comment]
Hi, 

Ok, thanks, I'll ask to my admin.
Cheers

C.

**Comment by xiaodaidaidai** [comment]
Hello, I encountered a similar error while processing data. Could you please help me take a look? Thank you very much
> ## Make plots
> mat_r1 <- getMapMat(stats_per_sample_r1[1], stats_per_sample_r1[2], stats_per_sample_r1[3], stats_per_sample_r1[4])
Error in getMapMat(stats_per_sample_r1[1], stats_per_sample_r1[2], stats_per_sample_r1[3],  :
  n.map.glob + n.map.loc == n.map is not TRUE
Calls: getMapMat -> stopifnot
Execution halted
